name: riderapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.8
  file_picker: ^8.0.3
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
